= Arcade project

* Arcade is a gaming platform: a program that lets the user choose a game to play and keeps a register of player scores.

* To be able to deal with the elements of Arcade at run-time, the graphic libraries and the games are implemented as dynamic libraries, loaded at runtime.

* Each GUI available for the program are used as a shared library that will be loaded and used dynamically by the main
program.

== Graphic Libraries

* libcaca
* SFML
* SDL2

== Usage

* `./arcade -h`
* `./arcade ./lib_arcade_libcaca.so`
* The games are available in the `./games` directory
* The graphic libraries are in the `./lib` directory

== Documentation

All the documentation files are in the ./doc folder

* Class diagram (UML) (pdf)
* Documentation to implement the Arcade Project (pdf)

== The teams

The games and libraries are compatible with each group

.Our Team

* Paul BEAUDUC : `paul.beauduc@epitech.eu`
* Tony DELAPIERRE: `tony.delapierre@epitech.eu`
* Joseph CHARTOIS: `joseph.chartois@epitech.eu`

.First team

* Théodore DAIGNAN FORNIER DE LACHAUX: `theodore.daignan-fornier-de-lachaux@epitech.eu`
* Flavien PERROCHEAU: `flavien.perrocheau@epitech.eu`
* Lib graphic: SFML, libcaca, ncurse
* Game: Nibbler

.Second team

* Jules BLANCHET: `jules.blanchet@epitech.eu`
* Dylan GARINEAUD: `dylan.garineaud@epitech.eu`
* Lib graphic: SFML, SDL, ncurse
* Game: Nibbler 
